import {
  Badge,
  BadgeRarity,
  BadgeCategory,
  BadgeConditionType,
} from '../entities/badge.entity';

export const BADGE_DEFINITIONS: Omit<Badge, 'id' | 'created_at' | 'updated_at' | 'userBadges'>[] = [
  {
    code: 'first_ascent',
    name: '初露锋芒',
    description: '完成第一条攀岩线路，开启你的攀岩之旅',
    rarity: BadgeRarity.COMMON,
    category: BadgeCategory.CLIMBING_FREQUENCY,
    conditions: [{ type: BadgeConditionType.TOTAL_ASCENTS, value: 1, operator: '>=' }],
    icon: 'mountain',
    color: '#22C55E',
    points: 10,
    is_active: true,
  },
  {
    code: 'climber_10',
    name: '攀岩新手',
    description: '累计完成10条线路',
    rarity: BadgeRarity.COMMON,
    category: BadgeCategory.CLIMBING_FREQUENCY,
    conditions: [{ type: BadgeConditionType.TOTAL_ASCENTS, value: 10, operator: '>=' }],
    icon: 'footprints',
    color: '#22C55E',
    points: 20,
    is_active: true,
  },
  {
    code: 'climber_50',
    name: '岩壁达人',
    description: '累计完成50条线路',
    rarity: BadgeRarity.COMMON,
    category: BadgeCategory.CLIMBING_FREQUENCY,
    conditions: [{ type: BadgeConditionType.TOTAL_ASCENTS, value: 50, operator: '>=' }],
    icon: 'trending-up',
    color: '#22C55E',
    points: 50,
    is_active: true,
  },
  {
    code: 'climber_200',
    name: '岩壁狂人',
    description: '累计完成200条线路',
    rarity: BadgeRarity.RARE,
    category: BadgeCategory.CLIMBING_FREQUENCY,
    conditions: [{ type: BadgeConditionType.TOTAL_ASCENTS, value: 200, operator: '>=' }],
    icon: 'zap',
    color: '#3B82F6',
    points: 150,
    is_active: true,
  },
  {
    code: 'climber_500',
    name: '传奇攀岩者',
    description: '累计完成500条线路',
    rarity: BadgeRarity.LEGENDARY,
    category: BadgeCategory.CLIMBING_FREQUENCY,
    conditions: [{ type: BadgeConditionType.TOTAL_ASCENTS, value: 500, operator: '>=' }],
    icon: 'trophy',
    color: '#F59E0B',
    points: 500,
    is_active: true,
  },
  {
    code: 'grade_v3',
    name: 'V3征服者',
    description: '完成V3难度线路',
    rarity: BadgeRarity.COMMON,
    category: BadgeCategory.GRADE_ACHIEVEMENT,
    conditions: [{ type: BadgeConditionType.MAX_GRADE, value: 3, operator: '>=' }],
    icon: 'target',
    color: '#22C55E',
    points: 15,
    is_active: true,
  },
  {
    code: 'grade_v5',
    name: 'V5攀登者',
    description: '完成V5难度线路',
    rarity: BadgeRarity.COMMON,
    category: BadgeCategory.GRADE_ACHIEVEMENT,
    conditions: [{ type: BadgeConditionType.MAX_GRADE, value: 5, operator: '>=' }],
    icon: 'flag',
    color: '#22C55E',
    points: 30,
    is_active: true,
  },
  {
    code: 'grade_v7',
    name: 'V7精英',
    description: '完成V7难度线路',
    rarity: BadgeRarity.RARE,
    category: BadgeCategory.GRADE_ACHIEVEMENT,
    conditions: [{ type: BadgeConditionType.MAX_GRADE, value: 7, operator: '>=' }],
    icon: 'award',
    color: '#3B82F6',
    points: 100,
    is_active: true,
  },
  {
    code: 'grade_v10',
    name: 'V10大师',
    description: '完成V10难度线路',
    rarity: BadgeRarity.LEGENDARY,
    category: BadgeCategory.GRADE_ACHIEVEMENT,
    conditions: [{ type: BadgeConditionType.MAX_GRADE, value: 10, operator: '>=' }],
    icon: 'crown',
    color: '#F59E0B',
    points: 300,
    is_active: true,
  },
  {
    code: 'streak_7',
    name: '周周坚持',
    description: '连续打卡7天',
    rarity: BadgeRarity.COMMON,
    category: BadgeCategory.CHECKIN_STREAK,
    conditions: [{ type: BadgeConditionType.CHECKIN_STREAK, value: 7, operator: '>=' }],
    icon: 'calendar',
    color: '#22C55E',
    points: 25,
    is_active: true,
  },
  {
    code: 'streak_30',
    name: '月度达人',
    description: '连续打卡30天',
    rarity: BadgeRarity.RARE,
    category: BadgeCategory.CHECKIN_STREAK,
    conditions: [{ type: BadgeConditionType.CHECKIN_STREAK, value: 30, operator: '>=' }],
    icon: 'flame',
    color: '#3B82F6',
    points: 120,
    is_active: true,
  },
  {
    code: 'streak_100',
    name: '百日战神',
    description: '连续打卡100天',
    rarity: BadgeRarity.LEGENDARY,
    category: BadgeCategory.CHECKIN_STREAK,
    conditions: [{ type: BadgeConditionType.CHECKIN_STREAK, value: 100, operator: '>=' }],
    icon: 'sunrise',
    color: '#F59E0B',
    points: 400,
    is_active: true,
  },
  {
    code: 'social_commenter',
    name: '积极评论者',
    description: '发布20条评论',
    rarity: BadgeRarity.COMMON,
    category: BadgeCategory.SOCIAL_INTERACTION,
    conditions: [{ type: BadgeConditionType.TOTAL_COMMENTS, value: 20, operator: '>=' }],
    icon: 'message-circle',
    color: '#22C55E',
    points: 20,
    is_active: true,
  },
  {
    code: 'social_popular',
    name: '人气攀岩者',
    description: '获得100个点赞',
    rarity: BadgeRarity.RARE,
    category: BadgeCategory.SOCIAL_INTERACTION,
    conditions: [{ type: BadgeConditionType.TOTAL_LIKES, value: 100, operator: '>=' }],
    icon: 'heart',
    color: '#3B82F6',
    points: 100,
    is_active: true,
  },
  {
    code: 'flash_master',
    name: 'Flash大师',
    description: '一次性完攀（Flash）20条线路',
    rarity: BadgeRarity.RARE,
    category: BadgeCategory.CLIMBING_FREQUENCY,
    conditions: [{ type: BadgeConditionType.FLASH_COUNT, value: 20, operator: '>=' }],
    icon: 'zap',
    color: '#3B82F6',
    points: 150,
    is_active: true,
  },
  {
    code: 'onsight_pro',
    name: 'Onsight专家',
    description: '首次尝试即完攀（Onsight）10条线路',
    rarity: BadgeRarity.LEGENDARY,
    category: BadgeCategory.CLIMBING_FREQUENCY,
    conditions: [{ type: BadgeConditionType.ONSIGHT_COUNT, value: 10, operator: '>=' }],
    icon: 'sparkles',
    color: '#F59E0B',
    points: 350,
    is_active: true,
  },
  {
    code: 'setter_beginner',
    name: '定线新秀',
    description: '作为定线员发布5条线路',
    rarity: BadgeRarity.COMMON,
    category: BadgeCategory.SPECIAL,
    conditions: [{ type: BadgeConditionType.ROUTES_SET, value: 5, operator: '>=' }],
    icon: 'map-pin',
    color: '#22C55E',
    points: 40,
    is_active: true,
  },
  {
    code: 'veteran_1year',
    name: '岩场老兵',
    description: '活跃攀岩满1年',
    rarity: BadgeRarity.RARE,
    category: BadgeCategory.SPECIAL,
    conditions: [{ type: BadgeConditionType.MONTHS_ACTIVE, value: 12, operator: '>=' }],
    icon: 'clock',
    color: '#3B82F6',
    points: 200,
    is_active: true,
  },
];
